### ISSUE TITLE
Issue of multiprocessing when training

### ISSUE THREAD

**Issue by michaelliyunhao** [Khrylx/RFC#3]
Hi,
Thanks for sharing this excellent work.
I met some problems when runing the training code about multiprocessing. The training code "python motion_imitation/motion_im.py --cfg 0506 --num_threads <max_num_CPU_threads_you_have>" works well when I only use one cpu core. But it stuck when I set the num_threads over 1(such as 2,4,12), the problem seems to be happened in "agent.py":  "pod, worker_memory, worker_logger = queue.get()" when the ppo algorithm starts sampling.
The multiprocessing process seems work okay in the first sampling iteration, but the queue start to be empty in the second iteration and then the whole training process stuck.
![image](https://user-images.githubusercontent.com/46719682/115988120-cd495e80-a5ea-11eb-8e7b-056b26ac8d1b.png)
I'm not familiar with gym and multiprocessing, do you know how to fix it?

Best Regards.

**Comment by Khrylx** [comment]
Hi,

You can try to set `export OMP_NUM_THREADS=1` in your .bashrc.
Also, for some pytorch version such as 1.12, such mutliprocessing problem can happen. You can try to update to newer pytorch version.

**Comment by michaelliyunhao** [comment]
> Hi,
> 
> You can try to set `export OMP_NUM_THREADS=1` in your .bashrc.
> Also, for some pytorch version such as 1.12, such mutliprocessing problem can happen. You can try to update to newer pytorch version.

**Comment by michaelliyunhao** [comment]
Thanks! Setting export OMP_NUM_THREADS=1 really works.
