### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by lucasjinreal** [Khrylx/RFC#4]
https://github.com/Khrylx/RFC/blob/04ad8f8969fb82fafb88666d2640484eba763ab4/khrylib/mocap/pose.py#L3

there is no such file?

**Comment by Khrylx** [comment]
Hi, have you installed the bvh package in the requirement?
https://github.com/Khrylx/RFC/blob/04ad8f8969fb82fafb88666d2640484eba763ab4/requirements.txt#L3

**Comment by lucasjinreal** [comment]
Oh, damn it, I didn't relise it was a lib..... sorry for my blind eyes.

**Comment by lucasjinreal** [comment]
@Khrylx However, may I ask you a question about applications on RL methods? 

It seems RFC just train on a certain clip and imitate it. (correct me if am wrong). Now I just wonder, in real world, we might don't want every single action have to train a model and run on it. we might want a unified model that train on millions of mocap data,
and imitation on novel scenarios. Is that possible to do it? By How?

**Comment by Garfield-kh** [comment]
@jinfagang 
Dynamics-Regulated Kinematic Policy for Egocentric Pose Estimation
SimPoE Simulated Character Control for 3D Human Pose Estimation
UniCon Universal Neural Controller For Physics-based Character Motion
SuperTrack Motion Tracking for Physically Simulated Characters using Supervised Learning

**Comment by lucasjinreal** [comment]
@Garfield-kh thanks. dpes posetriplet also want achieve this goal? which method is sota and opensourced the code?

**Comment by Garfield-kh** [comment]
[Dynamics-Regulated Kinematic Policy for Egocentric Pose Estimation](https://github.com/KlabCMU/kin-poly) is opensoured, the other three not yet..

**Comment by lucasjinreal** [comment]
@Garfield-kh thanks. this work based on ego motion, I mainly focus on rough 3d pose as input

**Comment by Garfield-kh** [comment]
you can try changing the dataset from ego motion to pose estimation...

**Comment by lucasjinreal** [comment]
@Garfield-kh make sense
